spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java1904?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false



mybatis:
  mapper-locations: classpath:/mapper/*.xml


#logging:
#  file: d://logs//all.log

